---

- name: "PREREQ | If required install libselinux package to manage file changes."
  ansible.builtin.package:
      name: python3-libselinux
      state: present
  when:
      - '"python3-libselinux" not in ansible_facts.packages'