---
###### 2.1.x time synchronization and chrony
- name: "2.1.1 | PATCH | Ensure time synchronization is in use"
  ansible.builtin.package:
      name: chrony
      state: present
  when:
      - amzn2023cis_rule_2_1_1
      - not system_is_container
  tags:
      - level1-server
      - patch
      - rule_2.1.1
      - nist_sp800-53r5_AU-3
      - nist_sp800-53r5_AU-12

- name: "2.1.2 | PATCH | Ensure chrony is configured"
  block:
      - name: "2.1.2 | PATCH | Ensure chrony is configured | Set configuration"
        ansible.builtin.template:
            src: etc/chrony.conf.j2
            dest: /etc/chrony.d/chrony.conf
            owner: root
            group: root
            mode: '0644'

      - name: "2.1.2 | PATCH | Ensure chrony is configured | modify /etc/sysconfig/chronyd | 1"
        ansible.builtin.lineinfile:
            path: /etc/sysconfig/chronyd
            regexp: "^(#)?OPTIONS"
            line: "OPTIONS=\"-u chrony\""
            create: true
            mode: '0644'
  when:
      - amzn2023cis_rule_2_1_2
      - not system_is_container
  tags:
      - level1-server
      - patch
      - rule_2.1.2
      - nist_sp800-53r5_AU-3
      - nist_sp800-53r5_AU-12


#### 2.2.x 

- name: "2.2.2 | PATCH | Ensure Avahi Server is not installed"
  ansible.builtin.package:
      name:
          - avahi-autoipd
          - avahi
      state: absent
  when:
      - amzn2023cis_rule_2_2_2
      - not amzn2023cis_avahi_server
      - "'avahi' in ansible_facts.packages or 'avahi-autopd' in ansible_facts.packages"
  tags:
      - level1-server
      - patch
      - avahi
      - rule_2.2.2

- name: "2.2.3 | PATCH | Ensure Print server is not installed"
  ansible.builtin.package:
      name: cups
      state: absent
  when:
      - not amzn2023cis_cups_server
      - "'cups' in ansible_facts.packages"
      - amzn2023cis_rule_2_2_3
  tags:
      - level1-server
      - patch
      - cups
      - rule_2.2.3
      - nist_sp800-53r5_CM-7

- name: "2.2.4 | PATCH | Ensure DHCP Server is not installed"
  ansible.builtin.package:
      name: dhcp-server
      state: absent
  when:
      - not amzn2023cis_dhcp_server
      - "'dhcp-server' in ansible_facts.packages"
      - amzn2023cis_rule_2_2_4
  tags:
      - level1-server
      - patch
      - dhcp
      - rule_2.2.4
      - nist_sp800-53r5_CM-7

- name: "2.2.5 | PATCH | Ensure DNS Server is not installed"
  ansible.builtin.package:
      name: bind
      state: absent
  when:
      - not amzn2023cis_dns_server
      - "'bind' in ansible_facts.packages"
      - amzn2023cis_rule_2_2_5
  tags:
      - level1-server
      - patch
      - dns
      - rule_2.2.5
      - nist_sp800-53r5_CM-7

- name: "2.2.6 | PATCH | Ensure an FTP Server is not installed"
  ansible.builtin.package:
      name: vsftpd
      state: absent
  when:
      - not amzn2023cis_vsftpd_server
      - "'vsftpd' in ansible_facts.packages"
      - amzn2023cis_rule_2_2_6
  tags:
      - level1-server
      - patch
      - vsftpd
      - rule_2.2.6
      - nist_sp800-53r5_CM-7

- name: "2.2.7 | PACH | Ensure TFTP Server is not installed"
  ansible.builtin.package:
      name: tftp-server
      state: absent
  when:
      - not amzn2023cis_tftp_server
      - "'tftp-server' in ansible_facts.packages"
      - amzn2023cis_rule_2_2_7
  tags:
      - level1-server
      - patch
      - tftp
      - rule_2.2.7
      - nist_sp800-53r5_CM-7

- name: "2.2.8 | PATCH | Ensure a web server is not installed"
  block:
      - name: "2.2.8 | PATCH | Ensure a web server is not installed | Remove httpd server"
        ansible.builtin.package:
            name: httpd
            state: absent
        when:
            - not amzn2023cis_httpd_server
            - "'httpd' in ansible_facts.packages"

      - name: "2.2.8 | PATCH | Ensure a web server is not installed | Remove nginx server"
        ansible.builtin.package:
            name: nginx
            state: absent
        when:
            - not amzn2023cis_nginx_server
            - "'nginx' in ansible_facts.packages"
  when:
      - amzn2023cis_rule_2_2_8
  tags:
      - level1-server
      - patch
      - httpd
      - nginx
      - webserver
      - rule_2.2.8
      - nist_sp800-53r5_CM-7

- name: "2.2.9 | PATCH | Ensure IMAP and POP3 server is not installed"
  block:
      - name: "2.2.9 | PATCH | Ensure IMAP and POP3 server is not installed"
        ansible.builtin.package:
            name:
                - dovecot
            state: absent
        when:
            - not amzn2023cis_dovecot_server
            - "'dovecot' in ansible_facts.packages"

      - name: "2.2.9 | PATCH | Ensure IMAP and POP3 server is not installed"
        ansible.builtin.package:
            name:
                - cyrus-imapd
            state: absent
        when:
            - not amzn2023cis_imap_server
            - "'cyrus-imapd' in ansible_facts.packages"

  when:
      - amzn2023cis_rule_2_2_9
  tags:
      - level1-server
      - patch
      - dovecot
      - imap
      - pop3
      - rule_2.2.9
      - nist_sp800-53r5_CM-7

- name: "2.2.10 | PATCH | Ensure Samba is not installed"
  ansible.builtin.package:
      name: samba
      state: absent
  when:
      - not amzn2023cis_samba_server
      - "'samba' in ansible_facts.packages"
      - amzn2023cis_rule_2_2_10
  tags:
      - level1-server
      - patch
      - samba
      - rule_2.2.10
      - nist_sp800-53r5_CM-7

- name: "2.2.11 | PATCH | Ensure HTTP Proxy Server is not installed"
  ansible.builtin.package:
      name: squid
      state: absent
  when:
      - not amzn2023cis_squid_server
      - "'squid' in ansible_facts.packages"
      - amzn2023cis_rule_2_2_11
  tags:
      - level1-server
      - patch
      - squid
      - rule_2.2.11
      - nist_sp800-53r5_CM-7

- name: "2.2.12 | PATCH | Ensure net-snmp is not installed or smpd service is not enabled"
  block:
      - name: "2.2.12 | PATCH | Ensure net-snmp is not installed or smpd service is not enabled | remove package"
        ansible.builtin.package:
            name: net-snmp
            state: absent
        when:
            - amzn2023cis_remove_snmp

      - name: "2.2.12 | PATCH | Ensure net-snmp is not installed or smpd service is not enabled | mask service"
        ansible.builtin.systemd:
            name: net-snmp
            state: stopped
            masked: true
  when:
      - not amzn2023cis_snmp_server
      - "'net-snmp' in ansible_facts.packages"
      - amzn2023cis_rule_2_2_12
  tags:
      - level1-server
      - patch
      - snmp
      - rule_2.2.12
      - nist_sp800-53r5_CM-7

- name: "2.2.13 | PATCH | Ensure telnet-server is not installed"
  ansible.builtin.package:
      name: telnet-server
      state: absent
  when:
      - not amzn2023cis_telnet_server
      - "'telnet-server' in ansible_facts.packages"
      - amzn2023cis_rule_2_2_13
  tags:
      - level1-server
      - patch
      - telnet
      - rule_2.2.13
      - nist_sp800-53r5_CM-7

- name: "2.2.14 | PATCH | Ensure dnsmasq is not installed"
  ansible.builtin.package:
      name: dnsmasq
      state: absent
  when:
      - not amzn2023cis_dnsmasq_server
      - "'dnsmasq' in ansible_facts.packages"
      - amzn2023cis_rule_2_2_14
  tags:
      - level1-server
      - patch
      - dnsmasq
      - rule_2.2.14
      - nist_sp800-53r5_CM-7

- name: "2.2.15 | PATCH | Ensure mail transfer agent is configured for local-only mode"
  ansible.builtin.lineinfile:
      path: /etc/postfix/main.cf
      regexp: "^(#)?inet_interfaces"
      line: "inet_interfaces = loopback-only"
  notify: Restart postfix
  when:
      - not amzn2023cis_is_mail_server
      - "'postfix' in ansible_facts.packages"
      - amzn2023cis_rule_2_2_15
  tags:
      - level1-server
      - patch
      - postfix
      - rule_2.2.15
      - nist_sp800-53r5_CM-7

# The name title of the service says mask the service, but the fix allows for both options
# Options available in default/main if to remove the package default is false just mask the server service
- name: "2.2.16 | PATCH | Ensure nfs-utils is not installed or the nfs-server service is masked"
  block:
      - name: "2.2.16 | PATCH | Ensure nfs-utils is not installed or the nfs-server service is masked | remove package"
        ansible.builtin.package:
            name: nfs-utils
            state: absent
        when:
            - amzn2023cis_nfs_server == "remove"

      - name: "2.2.16 | PATCH | Ensure nfs-utils is not installed or the nfs-server service is masked | mask service"
        ansible.builtin.systemd:
            name: nfs-server
            masked: true
            state: stopped
            daemon_reload: true
        when:
            - amzn2023cis_nfs_server == "mask"
  when:
      - "'nfs-utils' in ansible_facts.packages"
      - amzn2023cis_rule_2_2_16
  tags:
      - level1-server
      - patch
      - nfs
      - services
      - rule_2.2.16
      - nist_sp800-53r5_CM-6
      - nist_sp800-53r5_CM-7

# The name title of the service says mask the service, but the fix allows for both options
# Options available in default/main if to remove the package default is false just mask the server service
- name: "2.2.17 | PATCH | Ensure rpcbind is not installed or the rpcbind services are masked"
  block:
      - name: "2.2.17 | PATCH | Ensure rpcbind is not installed or the rpcbind services are masked | remove package"
        ansible.builtin.package:
            name: rpcbind
            state: absent
        when:
            - amzn2023cis_rpc_server == "remove"

      - name: "2.2.17 | PATCH | Ensure rpcbind is not installed or the rpcbind services are masked | mask socket"
        ansible.builtin.systemd:
            name: rpcbind.socket
            masked: true
            state: stopped
            daemon_reload: true
        when:
            - amzn2023cis_rpc_server == "mask"

      - name: "2.2.17 | PATCH | Ensure rpcbind is not installed or the rpcbind services are masked | mask service"
        ansible.builtin.systemd:
            name: rpcbind.service
            masked: true
            state: stopped
            daemon_reload: true
        when:
            - amzn2023cis_rpc_server == "mask"
  when:
      - "'rpcbind' in ansible_facts.packages"
      - amzn2023cis_rule_2_2_17
  tags:
      - level1-server
      - patch
      - rpc
      - rule_2.2.17
      - nist_sp800-53r5_CM-6
      - nist_sp800-53r5_CM-7

# The name title of the service says mask the service, but the fix allows for both options
# Options available in default/main if to remove the package default is false just mask the server service
- name: "2.2.18 | PATCH | Ensure rsync-daemon is not installed or the rsyncd service is masked "
  block:
      - name: "2.2.18 | PATCH | Ensure rsync-daemon is not installed or the rsync service is masked | remove package"
        ansible.builtin.package:
            name: rsync-daemon
            state: absent
        when:
            - amzn2023cis_rsync_server == "remove"
            - not amzn2023cis_use_rsync_service

      - name: "2.2.18 | PATCH | Ensure rsync-daemon is not installed or the rsyncd service is masked | mask service"
        ansible.builtin.systemd:
            name: rsyncd
            masked: true
            state: stopped
            daemon_reload: true
        when:
            - amzn2023cis_rsync_server == "mask"
  when:
      - "'rsync-daemon' in ansible_facts.packages"
      - amzn2023cis_rule_2_2_18
  tags:
      - level1-server
      - patch
      - rsync
      - rule_2.2.18
      - nist_sp800-53r5_CM-6
      - nist_sp800-53r5_CM-7

- name: "2.3.1 | PATCH | Ensure telnet client is not installed"
  ansible.builtin.package:
      name: telnet
      state: absent
  when:
      - not amzn2023cis_telnet_required
      - "'telnet' in ansible_facts.packages"
      - amzn2023cis_rule_2_3_1
  tags:
      - level1-server
      - patch
      - telnet
      - rule_2.3.1
      - nist_sp800-53r5_CM-7

- name: "2.3.2 | PATCH | Ensure LDAP client is not installed"
  ansible.builtin.package:
      name: openldap-clients
      state: absent
  when:
      - not amzn2023cis_openldap_clients_required
      - "'openldap-clients' in ansible_facts.packages"
      - amzn2023cis_rule_2_3_2
  tags:
      - level1-server
      - patch
      - ldap
      - rule_2.3.2
      - nist_sp800-53r5_CM-7

#### 2.3.x

- name: "2.3.3 | PATCH | Ensure FTP client is not installed"
  ansible.builtin.package:
      name: ftp
      state: absent
  when:
      - not amzn2023cis_ftp_client
      - "'ftp' in ansible_facts.packages"
      - amzn2023cis_rule_2_3_3
  tags:
      - level1-server
      - patch
      - ftp
      - rule_2.3.3
      - nist_sp800-53r5_CM-7

#### 2.4.x 


- name: "2.4 | AUDIT | Ensure nonessential services listening on the system are removed or masked"
  block:
      - name: "2.4 | AUDIT | Ensure nonessential services listening on the system are removed or masked | Get list of services"
        ansible.builtin.shell: systemctl list-units --type=service
        changed_when: false
        failed_when: false
        check_mode: false
        register: amzn2023cis_2_4_services

      - name: "2.4 | AUDIT | Ensure nonessential services listening on the system are removed or masked | Get list of sockets"
        ansible.builtin.shell: systemctl list-units --type=sockets
        changed_when: false
        failed_when: false
        check_mode: false
        register: amzn2023cis_2_4_sockets

      - name: "2.4 | AUDIT | Ensure nonessential services listening on the system are removed or masked | Display list of services"
        ansible.builtin.debug:
            msg:
                - "Warning!! Below are the list of services and sockets, both active and inactive"
                - "Please review to make sure all are essential"
                - "{{ amzn2023cis_2_4_services.stdout_lines }}"
                - "{{ amzn2023cis_2_4_sockets.stdout_lines }}"

      - name: "2.4 | AUDIT | Ensure nonessential services listening on the system are removed or masked | Warn Count"
        ansible.builtin.import_tasks:
            file: warning_facts.yml
  vars:
      warn_control_id: '2.4'
  when:
      - amzn2023cis_rule_2_4
  tags:
      - level1-server
      - manual
      - audit
      - services
      - rule_2.4
      - nist_sp800-53r5_CM-7

